# Please refer to the wiki page located at https://github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https://discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding the main config file

[triggers]
[[triggers.command]]
		persistence = "120"

		identifier = "blind"
	[[triggers.command]]
		persistence = "18000"

		identifier = "mild_end"
		
[songs]
	[[songs.silence]]
		triggers = [ "command-mild_end" ]
		[[songs.silence]]
		triggers = [ "command-blind" ]
	[songs.universal]
