# Please refer to the wiki page located at https://github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https://discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding transitions
[[image]]
	time = "18000"
	fade_in = 0
	fade_out = 20
	opacity = 1.0
	scale_x = "7.2"
	scale_y = "4"
	horizontal_alignment = "center"
	vertical_alignment = "center"
	x = 0
	y = 0
	play_once = false
	vague = false
	triggers = [ "command-mild_end" ]
	name = "end.png"
[[image]]
	time = "120"
	fade_in = 20
	fade_out = 20
	opacity = 1.0
	scale_x = "7"
	scale_y = "4"
	horizontal_alignment = "center"
	vertical_alignment = "center"
	x = 0
	y = 0
	play_once = false
	vague = false
	triggers = [ "command-blind" ]
	name = "blind.png"